# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
  get-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get time
        run: echo $(date +%Y%m%d-%x)
