# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      name:
        description: input name
        required: false

jobs:
  get-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get time
        run: |
          echo ${$INPUT_NAME:-$(date +%Y%m%d-%s)}
