name: Continue on Error & needs

on:
  workflow_dispatch:

jobs:
  step1:
    runs-on: ubuntu-latest
    outputs:
      need_release: ${{ steps.next-step.outputs.need_release }}
    steps:
      - name: fail step
        id: error_step
        run: exit 1
        continue-on-error: true
      - name: next step
        id: next-step
        if: steps.error_step.outcome == 'failure'
        run: echo "hoge"
  step2:
    runs-on: ubuntu-latest
    needs: step1
    if: ${{ needs.step1.outputs.need_release == 'true' }}
    env:
      NEEDS_CONTEXT: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS_CONTEXT"
      - name: hoge
        run: echo "run"
